---
- hosts: ubuntu
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot Servers if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies no longer required
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
